<?php 
if(isset($_SESSION['username']))
{
   unset($_SESSION['username']);
}
if(isset($_SESSION['account_type']))
{
	unset($_SESSION['account_type']);
}
header("location:index.php?content=home");
?>